<?php //$_product = $this->_getProduct();?>
 <?php $_product = Mage::getModel('core/session')->getProductToShoppingCart() ?>
    <?php if ($_product && $_product->getId()): ?>
    
	    <script>
	    /* <![CDATA[ */
	    ga('require', 'ec');
	    ga('ec:addProduct', {               // Provide product details in a productFieldObject.
	    	  'id': '<?php echo $_product->getId();?>',         // Product ID (string).
	    	  'name': '<?php echo $_product->getName();?>', 	// Product name (string).
	    	  'category': '<?php echo $_product->getData("category_name");?>',
	    	    //'brand': product.brand,
	    	    //'variant': product.variant,
	    	    'price': <?php echo $_product->getData("price");?>,
	    	    'quantity': <?php echo $_product->getData("qty");?>
	    	});

	    ga('ec:setAction', 'add');
	    ga('send', 'event', 'UX', 'click', 'add to cart'); 
	    /* ]]> */
	 
	    </script>
	     <?php Mage::getModel('core/session')->unsProductToShoppingCart(); ?>
	<?php endif; ?>
  

