<?php /* @var $this Fooman_GoogleAnalyticsPlus_Block_Universal */?>
<?php if ($this->shouldInclude()): ?>
    <?php $altUniversal = $this->getAlternativeUniversalAccount(); ?>
    <!-- Google Analytics -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','<?php echo $this->getAnalyticsLocation(); ?>','ga');

        ga('create', '<?php echo $this->getUniversalAccount(); ?>',<?php echo $this->getUniversalParams(); ?>);
        <?php if ($altUniversal):?>
            ga('create', '<?php echo $altUniversal; ?>',<?php echo $this->getUniversalParams(true); ?>);
        <?php endif;?>

        <?php if($this->getUniversalAnonymise()):?>
            ga('set', 'anonymizeIp', true);
            <?php if ($altUniversal):?>
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.set', 'anonymizeIp', true);
            <?php endif;?>
        <?php endif;?>
        <?php if($this->getUniversalDisplayAdvertising()):?>
            ga('require', 'displayfeatures'<?php if($this->getUniversalDisplayAdvertisingCookieName()):?>, undefined, { cookieName: '<?php echo $this->getUniversalDisplayAdvertisingCookieName(); ?>' }<?php endif; ?>);
            <?php if ($altUniversal):?>
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.require', 'displayfeatures'<?php if($this->getUniversalDisplayAdvertisingCookieName()):?>, undefined, { cookieName: '<?php echo $this->getUniversalDisplayAdvertisingCookieName(); ?>' }<?php endif; ?>);
            <?php endif;?>
        <?php endif;?>
        <?php if($this->isEnhancedLinkAttrEnabled()):?>
            ga('require', 'linkid');
            <?php if ($altUniversal):?>
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.require', 'linkid');
            <?php endif;?>
        <?php endif;?>
        ga('send', 'pageview', '<?php echo $this->getPageName(); ?>');
        <?php if ($altUniversal):?>
            ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.send', 'pageview', '<?php echo $this->getPageName(); ?>');
        <?php endif;?>

        <?php if($this->isAddtoCartEnabled()):?>
	        <?php $_product = Mage::helper('googleanalyticsplus')->getProductAddedToCart();?>
	        <?php if ($_product): ?>
	         ga('require', 'ec');
	         ga('ec:addProduct', {
	          'id': '<?php echo $_product->getId();?>',
	          'name': '<?php echo $this->jsQuoteEscape($_product->getName());?>',
	          'category': '<?php echo $this->jsQuoteEscape($_product->getData("category_name"));?>',
	          'brand': '<?php echo $this->jsQuoteEscape($_product->getData("brand_name"));?>',
	           //'variant': product.variant,
	          'price': <?php echo $_product->getData("price");?>,
	          'quantity': <?php echo $_product->getData("qty");?>,
	         });
	         ga('ec:setAction', 'add');
	         ga('send', 'event', 'enhanced ecommerce', 'button click', 'add to cart');
	        <?php endif; ?>
	    <?php endif; ?>

        <?php if ($this->isAddtoNewsletterEnabled() && Mage::helper('googleanalyticsplus')->getAddedToNewsletter()): ?>
         ga('send', 'event', 'Newsletter', 'Subscription');
        <?php endif; ?>
    </script>
    
    
    <?php if($this->isSuccessPage()):?>
        <?php $order = $this->_getOrder();?>
            <?php
            $shipping = Mage::helper('googleanalyticsplus')->convert($order, 'shipping_amount');
            $tax = Mage::helper('googleanalyticsplus')->convert($order, 'tax_amount');
            $revenue =  Mage::helper('googleanalyticsplus')->convert($order, 'grand_total');
            $revenue -= (($this->shouldExcludeShipping())? $shipping : 0);
            $revenue -= (($this->shouldExcludeTax())? $tax : 0);
            $coupon  = $this->jsQuoteEscape($order->getData("coupon_code"));
            
            $transactionDetails = "{
            'id': '". $this->jsQuoteEscape($order->getIncrementId()) ."',
            'affiliation': '". $this->jsQuoteEscape(Mage::app()->getStore()->getName()) ."',
            'revenue': '". $revenue ."',
            'shipping': '". $shipping ."',
            'tax': '". $tax ."',
            'coupon': '". $coupon . "'		
            }";
            ?>
        <script>
            /* <![CDATA[ */
        ga('require', 'ec');
        ga('set', 'currencyCode', 'EUR'); 
       
        <?php foreach ($order->getAllVisibleItems() as $item):?>
	        <?php 
	        $_sku = $item->getSku();
	        $_product = Mage::getModel('catalog/product')->loadByAttribute('sku',$_sku);
	        $_manufacturerName = $_product->getAttributeText('brand');
	        ?>
	            <?php $itemDetails = "{
	                'id': '".$this->jsQuoteEscape($order->getIncrementId()) ."',
	                'name': '". $this->jsQuoteEscape($item->getName()) ."',
	                'sku': '". $this->jsQuoteEscape($item->getSku()) ."',
	        		'brand': '". $this->jsQuoteEscape($_manufacturerName) ."',
	                'price': '". Mage::helper('googleanalyticsplus')->convert($item, 'price', $order->getOrderCurrencyCode()) ."',
	                'quantity': '". (int)$item->getQtyOrdered() ."',
	                'category': '". $this->jsQuoteEscape($this->getCategory($item)) ."'
	                }";
	                ?>

            ga('ec:addProduct', <?php echo $itemDetails?>);
            ga('ec:setAction', 'purchase', <?php echo $transactionDetails?>);
            ga('send', 'pageview'); 
        <?php endforeach;?>

            /* ]]> */
        </script>
    <?php endif; ?>
    <!-- End Google Analytics -->
<?php endif; ?>
